using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:DisDogSharp.ApplicationCommands.ApplicationCommandsExtension.s_registeredCommands")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.ApplicationCommandsExtension.UpdateAsync~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DisDogSharp.ApplicationCommands.ApplicationCommandsExtension.GlobalCommands")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DisDogSharp.ApplicationCommands.ApplicationCommandsExtension.GuildCommands")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~P:DisDogSharp.ApplicationCommands.ApplicationCommandsExtension.RegisteredCommands")]
[assembly: SuppressMessage("Performance", "CA1842:Do not use 'WhenAll' with a single task", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.DefaultHelpModule.DefaultHelpAsync(DisDogSharp.ApplicationCommands.Context.InteractionContext,System.String,System.String,System.String)~System.Threading.Tasks.Task")]
[assembly:
	SuppressMessage("Performance", "CA1842:Do not use 'WhenAll' with a single task", Justification = "<Pending>", Scope = "member",
		Target = "~M:DisDogSharp.ApplicationCommands.DefaultHelpModule.DefaultHelpAutoCompleteLevelOneProvider.Provider(DisDogSharp.ApplicationCommands.Context.AutocompleteContext)~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{DisDogSharp.Entities.DiscordApplicationCommandAutocompleteChoice}}")]
[assembly:
	SuppressMessage("Performance", "CA1842:Do not use 'WhenAll' with a single task", Justification = "<Pending>", Scope = "member",
		Target = "~M:DisDogSharp.ApplicationCommands.DefaultHelpModule.DefaultHelpAutoCompleteLevelTwoProvider.Provider(DisDogSharp.ApplicationCommands.Context.AutocompleteContext)~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{DisDogSharp.Entities.DiscordApplicationCommandAutocompleteChoice}}")]
[assembly:
	SuppressMessage("Performance", "CA1842:Do not use 'WhenAll' with a single task", Justification = "<Pending>", Scope = "member",
		Target = "~M:DisDogSharp.ApplicationCommands.DefaultHelpModule.DefaultHelpAutoCompleteProvider.Provider(DisDogSharp.ApplicationCommands.Context.AutocompleteContext)~System.Threading.Tasks.Task{System.Collections.Generic.IEnumerable{DisDogSharp.Entities.DiscordApplicationCommandAutocompleteChoice}}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.DefaultHelpModule.DefaultHelpAsync(DisDogSharp.ApplicationCommands.Context.InteractionContext,System.String,System.String,System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.Workers.RegistrationWorker.BuildGlobalCreateList(DisDogSharp.DiscordClient,System.Collections.Generic.List{DisDogSharp.Entities.DiscordApplicationCommand})~System.Collections.Generic.List{DisDogSharp.Entities.DiscordApplicationCommand}")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.Workers.RegistrationWorker.BuildGlobalDeleteList(DisDogSharp.DiscordClient,System.Collections.Generic.List{DisDogSharp.Entities.DiscordApplicationCommand})~System.Collections.Generic.List{System.UInt64}")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.Workers.RegistrationWorker.BuildGuildCreateList(DisDogSharp.DiscordClient,System.UInt64,System.Collections.Generic.List{DisDogSharp.Entities.DiscordApplicationCommand})~System.Collections.Generic.List{DisDogSharp.Entities.DiscordApplicationCommand}")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.Workers.RegistrationWorker.BuildGuildDeleteList(DisDogSharp.DiscordClient,System.UInt64,System.Collections.Generic.List{DisDogSharp.Entities.DiscordApplicationCommand})~System.Collections.Generic.List{System.UInt64}")]
[assembly: SuppressMessage("Usage", "DCS0102:[Discord] Deprecated", Justification = "<Pending>")]
[assembly: SuppressMessage("Usage", "DCS0101:[Discord] InExperiment", Justification = "<Pending>")]
[assembly: SuppressMessage("Usage", "DCS0103:[Discord] InExperiment", Justification = "<Pending>")]
[assembly: SuppressMessage("Usage", "DCS0001:[Discord] InExperiment", Justification = "<Pending>")]
[assembly: SuppressMessage("Usage", "DCS0002:[Discord] InExperiment", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.ApplicationCommandsModuleConfiguration.#ctor(System.Type,System.Action{DisDogSharp.ApplicationCommands.Context.ApplicationCommandsTranslationContext})")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.Attributes.ApplicationCommandModuleLifespanAttribute.#ctor(DisDogSharp.ApplicationCommands.Enums.ApplicationCommandModuleLifespan)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.Attributes.ApplicationCommandRequireBotPermissionsAttribute.#ctor(DisDogSharp.Enums.Permissions,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.Attributes.ApplicationCommandRequirePermissionsAttribute.#ctor(DisDogSharp.Enums.Permissions,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.Attributes.ApplicationCommandRequireUserPermissionsAttribute.#ctor(DisDogSharp.Enums.Permissions,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.Attributes.AutocompleteAttribute.#ctor(System.Type)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.Attributes.ChannelTypesAttribute.#ctor(DisDogSharp.Enums.ChannelType[])")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.Attributes.ChoiceNameAttribute.#ctor(System.String)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.Attributes.ChoiceProviderAttribute.#ctor(System.Type)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.Attributes.RequireAnyPermissionsAttribute.#ctor(DisDogSharp.Enums.Permissions[])")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.EventArgs.ContextMenuErrorEventArgs.#ctor(System.IServiceProvider)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.EventArgs.ContextMenuExecutedEventArgs.#ctor(System.IServiceProvider)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.EventArgs.SlashCommandErrorEventArgs.#ctor(System.IServiceProvider)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:DisDogSharp.ApplicationCommands.EventArgs.SlashCommandExecutedEventArgs.#ctor(System.IServiceProvider)")]
